title: "Alaaddin Güleç"
author: "Alaaddin Güleç"
description: "Teknoloji, Yapay Zeka ve Otomasyon üzerine makaleler ve ürün çözümleri"
baseurl: ""
url: "https://alaaddingulec.github.io"

# Menü (dropdown örneği)
navbar:
  - title: Çözümler
    url: /solutions
    children:
      - title: Bulut Çözümleri
        url: /solutions#cloud
      - title: IoT & Otomasyon
        url: /solutions#iot
      - title: Yapay Zeka
        url: /solutions#ai
  - title: Ürünler
    url: /products
  - title: Blog
    url: /blog
  - title: Hakkımızda
    url: /about
  - title: İletişim
    url: /contact

social-network-links:
  email: "alaaddingulec2012@hotmail.com"
  github: "alaaddingulec"
  linkedin: "kullaniciadiniz"

paginate: 6
