# Site Ayarları
title: Alaaddin Güleç
author: Alaaddin Güleç
description: >-
  Yazılım, Otomasyon ve Teknoloji Üzerine Notlar
baseurl: "" # Siteniz ana dizinde olduğu için bu boş kalmalı
url: "https://alaaddingulec.github.io" # Sitenizin adresi

# Sosyal Medya Linkleri (İsteğe bağlı, kendinize göre düzenleyin)
social-network-links:
  email: "alaaddingulec2012@hotmail.com"
  github: "alaaddingulec"
  linkedin: "kullaniciadiniz" # Kendi LinkedIn kullanıcı adınızı yazın

# Tema Ayarları
remote_theme: "daattali/beautiful-jekyll" # Bu satır temayı yüklüyor

# Menü Linkleri
navbar-links:
  - title: Ana Sayfa
    url: /
  - title: Hakkımda
    url: /about

# Sayfalama Ayarı
paginate: 5
