title: "Alaaddin Güleç Teknoloji"
author: "Alaaddin Güleç"
description: "Kurumsal teknoloji çözümleri, iletişim ve otomasyon"
baseurl: ""
url: "https://alaaddingulec.github.io"

social-network-links:
  email: "alaaddingulec2012@hotmail.com"
  github: "alaaddingulec"
  linkedin: "kullaniciadiniz"

# Tema kapalı; kendi layoutlarımızı kullanıyoruz
remote_theme: null

# Menü
navbar:
  - title: Çözümler
    url: /solutions
  - title: Ürünler
    url: /products
  - title: Blog
    url: /blog
  - title: Hakkımızda
    url: /about
  - title: İletişim
    url: /contact

paginate: 6
